
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://fed29.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: "UA-116690067-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Federico Angaramo"
title: "{ Federico Angaramo }"
description: "Blog and website of Federico Angaramo, blogging mainly for AI - ML - DevOps - Cloud. Opinions expressed are mine."
keywords: "federico, angaramo, fed29, personal, artificial, intelligence, ai, machine, learning, ml, cloud, microsoft, azure, devops"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "If you can't explain it simply, you don't understand it well enough."
  - text: "Where’s your will to be weird?"

me-img: "/img/me.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/sella.jpg"
    date: "February 2018 - Today"
    description: "AI Specialist @ Gruppo Banca Sella"
  - image: "/img/timeline/ismb_mit.jpg"
    date: "April 2016 - February 2018"
    description: "Researcher and SW Developer @ ISMB"
  - image: "/img/timeline/ms.jpg"
    date: "February 2015 - August 2015"
    description: "ISV Tech Support @ Microsoft Italy"
  - image: "/img/timeline/msc.jpg"
    date: "October 2013 - April 2017"
    description: "M.Sc. in Computer Science"
  - image: "/img/timeline/msp.jpg"
    date: "September 2013 - June 2017"
    description: "Microsoft Student Partner"
  - image: "/img/timeline/bsc.jpg"
    date: "October 2010 - October 2013"
    description: "Bachelor's degree"

################
# Publications #
################

papers:
  - year: 2018
    authors: F. Angaramo, C. Rossi
    title: Online clustering and classification for real-time event detection in Twitter
    link: 
    details: ISRAM 2018, Rochester, New York (USA) - 05/2018
  - year: 2017
    authors: J. Longhini, C. Rossi, C. Casetti, F. Angaramo
    title: A language-agnostic approach to exact informative tweets during emergency situations
    link: http://ieeexplore.ieee.org/document/8258372/
    details: IEEE Big Data 2017, Boston, Massachusetts (USA) - 12/2017
  - year: 2017
    authors: A. Gobbi, A. Alikadic, K. Ylinen, F. Angaramo, C. Furlanello
    title: A heat wave forecast system for Europe
    link: http://ieeexplore.ieee.org/document/8258371/
    details: IEEE Big Data 2017, Boston, Massachusetts (USA) - 12/2017

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "federico.angaramo@outlook.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Federico Angaramo is an awesome person. He lives in Biella (Italy), where he works on Data Science and AI projects. In his spare time, Federico likes to ride his bike."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/federico.angaramo"
  - title: "twitter"
    url: "https://twitter.com/fed29"
  - title: "github"
    url: "https://github.com/fed29"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/404-gif-8.gif"

##################
# GPG on Keybase #
##################

#keybase-username: 
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Publications: 'publications'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
